const theText = "web js hi css"
document.write(`${theText}`)
console.log(theText)
console.log(theText.bold())
console.log(theText.link("https://www.naver.com"))
console.log(theText.length)
console.log(theText.toUpperCase())
console.log(theText.toLowerCase())
console.log(theText.indexOf("s"))
console.log(theText.lastIndexOf("s"))
console.log(theText.charAt(7))
console.log(theText.substring(4, 6))
console.log(theText.slice(7, 9))
console.log(theText.substr(10, 3))
console.log(theText.replace("hi", "bye"))
console.log(theText.concat("good"))
console.log(theText.split(" "))