document.write("<h1>D-day 계산기</h1>")
let today = new Date()
let afterDayYear = parseInt(prompt("연도를 입력하세요."))
let afterDayMonth = parseInt(prompt("월을 입력하세요."))
let afterDayDate = parseInt(prompt("일을 입력하세요."))
let afterDay = new Date(afterDayYear, afterDayMonth-1, afterDayDate)
let diffDay = afterDay.getTime() - today.getTime()
let dDay = Math.ceil(diffDay / 1000 / 60 / 60 / 24)
document.write(`${afterDayYear}년 ${afterDayMonth}월 ${afterDayDate}일까지 ${dDay}일 남았습니다.`)